name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: docker build -f ./image/Containerfile -t poetry-gitlab .

    - name: Sanity check
      run: docker run poetry-gitlab poetry --help
