FROM registry.fedoraproject.org/fedora-minimal@sha256:fb3f9c67f0aefa3d7a9f63fd8c3f373c86df57efb0128ee1fe6bf461bc803534

RUN microdnf -y upgrade
RUN microdnf -y install \
  python \
  git-core \
  golang \
  jq \
  krb5-devel \
  python3-wheel \
  libffi-devel \
  unzip \
  /usr/bin/gpg \
  /usr/bin/pip \
  /usr/bin/poetry \
  /usr/bin/make \
  /usr/bin/tox \
  /usr/bin/openssl

ADD . /src

# TODO: pin the aws-cli version with autoupdate
RUN gpg --import /src/image/awscli.pubkey \
  && curl \
  https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip \
  -o awscliv2.zip \
  && curl \
  https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig \
  -o awscliv2.sig \
  && gpg --verify awscliv2.sig awscliv2.zip \
  && unzip -q awscliv2.zip \
  && ./aws/install \
  && rm -rf aws awscliv2.sig awscliv2.zip

RUN mv /src/image/*CA.pem /etc/pki/ca-trust/source/anchors && update-ca-trust
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

RUN \
  cd /src/glab && \
  make && \
  mv -v bin/glab /usr/local/bin/glab && \
  cd /src/tkn && \
  make bin/tkn && \
  mv -v bin/tkn /usr/local/bin/tkn && \
  go clean -r -cache -modcache

ENTRYPOINT ["/bin/bash", "-c"]
